name: Run test suites

'on': [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install the dependencies
        run: yarn install
      - name: Code style test & validation
        run: yarn style
      - name: Run test suites
        run: yarn test
