name: tsc & lint test

'on':
  push:
  pull_request:
    branches:
      - main

jobs:
  lint_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installing the dependencies
        run: npm ci --silent
      - name: tsc & lint test
        run: npm run style
      - name: Next.js build
        run: npm run build
